import { NextResponse } from "next/server";
import { connectToDatabase } from "../../../lib/mongodb";
import Question from "../../../lib/models/Question";

const mathQuestions = [
  {
    "id": "MATH_001",
    "subject": "Mathematics",
    "chapter": "Sets and Functions",
    "topic": "Sets",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "If A = {1,2,3,4} and B = {3,4,5,6}, then A ∩ B is:",
    "options": ["{1,2}", "{3,4}", "{5,6}", "{1,6}"],
    "correctAnswer": "{3,4}",
    "solution": "Intersection contains common elements.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Intersection of sets"],
    "tags": ["sets", "basic"]
  },
  {
    "id": "MATH_002",
    "subject": "Mathematics",
    "chapter": "Trigonometric Functions",
    "topic": "Trigonometric Identities",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "The value of sin²θ + cos²θ is:",
    "options": ["0", "1", "2", "Depends on θ"],
    "correctAnswer": "1",
    "solution": "Fundamental trigonometric identity.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 30,
    "concepts": ["Basic identities"],
    "tags": ["trigonometry"]
  },
  {
    "id": "MATH_003",
    "subject": "Mathematics",
    "chapter": "Complex Numbers and Quadratic Equations",
    "topic": "Quadratic Equations",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "The roots of x² - 5x + 6 = 0 are:",
    "options": ["2,3", "1,6", "−2,−3", "5,6"],
    "correctAnswer": "2,3",
    "solution": "Factorization gives (x−2)(x−3)=0.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Quadratic roots"],
    "tags": ["quadratic"]
  },
  {
    "id": "MATH_004",
    "subject": "Mathematics",
    "chapter": "Permutations and Combinations",
    "topic": "Permutations",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "The number of ways to arrange 5 different books on a shelf is:",
    "options": ["25", "60", "120", "240"],
    "correctAnswer": "120",
    "solution": "5! = 120.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 50,
    "concepts": ["Permutations"],
    "tags": ["pnc"]
  },
  {
    "id": "MATH_005",
    "subject": "Mathematics",
    "chapter": "Binomial Theorem",
    "topic": "Expansion",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "The coefficient of x² in (1+x)^4 is:",
    "options": ["4", "6", "12", "24"],
    "correctAnswer": "6",
    "solution": "Using nCr term: 4C2 = 6.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Binomial coefficients"],
    "tags": ["binomial"]
  },
  {
    "id": "MATH_006",
    "subject": "Mathematics",
    "chapter": "Sequences and Series",
    "topic": "Arithmetic Progression",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "The 10th term of AP: 2,5,8,... is:",
    "options": ["29", "30", "31", "32"],
    "correctAnswer": "29",
    "solution": "a₁₀ = 2 + 9×3 = 29.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["AP nth term"],
    "tags": ["ap"]
  },
  {
    "id": "MATH_007",
    "subject": "Mathematics",
    "chapter": "Sequences and Series",
    "topic": "Geometric Progression",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "The sum of first 4 terms of GP 2,4,8,... is:",
    "options": ["28", "30", "32", "34"],
    "correctAnswer": "30",
    "solution": "2+4+8+16 = 30.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["GP sum"],
    "tags": ["gp"]
  },
  {
    "id": "MATH_008",
    "subject": "Mathematics",
    "chapter": "Straight Lines",
    "topic": "Slope",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Slope of line passing through (1,2) and (3,6) is:",
    "options": ["1", "2", "3", "4"],
    "correctAnswer": "2",
    "solution": "(6−2)/(3−1)=2.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Slope formula"],
    "tags": ["straight-lines"]
  },
  {
    "id": "MATH_009",
    "subject": "Mathematics",
    "chapter": "Probability",
    "topic": "Basic Probability",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Probability of getting a head when tossing a fair coin is:",
    "options": ["0", "1/4", "1/2", "1"],
    "correctAnswer": "1/2",
    "solution": "One favorable outcome out of two.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 30,
    "concepts": ["Basic probability"],
    "tags": ["probability"]
  },
  {
    "id": "MATH_010",
    "subject": "Mathematics",
    "chapter": "Mathematical Reasoning",
    "topic": "Logic",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "The negation of 'All birds can fly' is:",
    "options": [
      "No birds can fly",
      "Some birds cannot fly",
      "All birds cannot fly",
      "Some birds can fly"
    ],
    "correctAnswer": "Some birds cannot fly",
    "solution": "Negation of universal statement.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Logical negation"],
    "tags": ["reasoning"]
  },
  {
    "id": "MATH_011",
    "subject": "Mathematics",
    "chapter": "Complex Numbers and Quadratic Equations",
    "topic": "Complex Numbers",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "If i = √−1, then i^8 equals:",
    "options": ["1", "−1", "i", "−i"],
    "correctAnswer": "1",
    "solution": "i⁴ =1 so i⁸=1.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Powers of i"],
    "tags": ["complex"]
  },
  {
    "id": "MATH_012",
    "subject": "Mathematics",
    "chapter": "Binomial Theorem",
    "topic": "Middle Term",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "The middle term in expansion of (x+1)^6 is:",
    "options": ["15x³", "20x³", "15x²", "20x²"],
    "correctAnswer": "20x³",
    "solution": "Middle term is T₄ = 20x³.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Middle term"],
    "tags": ["binomial"]
  },
  {
    "id": "MATH_013",
    "subject": "Mathematics",
    "chapter": "Trigonometric Functions",
    "topic": "Angles",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "sin 90° equals:",
    "options": ["0", "1", "−1", "1/2"],
    "correctAnswer": "1",
    "solution": "Standard trigonometric value.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 20,
    "concepts": ["Standard angles"],
    "tags": ["trigonometry"]
  },
  {
    "id": "MATH_014",
    "subject": "Mathematics",
    "chapter": "Statistics",
    "topic": "Mean",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Mean of 2,4,6,8 is:",
    "options": ["4", "5", "6", "7"],
    "correctAnswer": "5",
    "solution": "Mean = 20/4 =5.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Arithmetic mean"],
    "tags": ["statistics"]
  },
  {
    "id": "MATH_015",
    "subject": "Mathematics",
    "chapter": "Straight Lines",
    "topic": "Equation of Line",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Equation of line with slope 2 passing through origin is:",
    "options": ["y=2x", "x=2y", "y=x+2", "2x+y=0"],
    "correctAnswer": "y=2x",
    "solution": "Slope-intercept form.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Line equation"],
    "tags": ["coordinate-geometry"]
  },
  {
    "id": "MATH_016",
    "subject": "Mathematics",
    "chapter": "Permutations and Combinations",
    "topic": "Combinations",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "The value of 5C2 is:",
    "options": ["5", "10", "15", "20"],
    "correctAnswer": "10",
    "solution": "5C2 = 10.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Combinations"],
    "tags": ["pnc"]
  },
  {
    "id": "MATH_017",
    "subject": "Mathematics",
    "chapter": "Sequences and Series",
    "topic": "Series",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Sum of first 5 natural numbers is:",
    "options": ["10", "15", "20", "25"],
    "correctAnswer": "15",
    "solution": "n(n+1)/2 = 15.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Series sum"],
    "tags": ["series"]
  },
  {
    "id": "MATH_018",
    "subject": "Mathematics",
    "chapter": "Probability",
    "topic": "Dice",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Probability of getting an even number on a die is:",
    "options": ["1/6", "1/3", "1/2", "2/3"],
    "correctAnswer": "1/2",
    "solution": "3 favorable outcomes out of 6.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Probability"],
    "tags": ["probability"]
  },
  {
    "id": "MATH_019",
    "subject": "Mathematics",
    "chapter": "Functions",
    "topic": "Domain and Range",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Domain of f(x)=1/(x−2) is:",
    "options": ["x≠2", "x=2", "x>2", "All real numbers"],
    "correctAnswer": "x≠2",
    "solution": "Denominator cannot be zero.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Domain"],
    "tags": ["functions"]
  },
  {
    "id": "MATH_020",
    "subject": "Mathematics",
    "chapter": "3D Geometry",
    "topic": "Coordinates",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Distance of point (3,4,12) from origin is:",
    "options": ["12", "13", "14", "15"],
    "correctAnswer": "13",
    "solution": "√(9+16+144)=13.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["3D distance"],
    "tags": ["3d-geometry"]
  },
  {
    "id": "MATH_021",
    "subject": "Mathematics",
    "chapter": "Quadratic Equations",
    "topic": "Roots",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Find the sum of roots of equation x² − 7x + 10 = 0.",
    "correctAnswer": 7,
    "solution": "Sum of roots = −b/a = 7.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 90,
    "concepts": ["Sum of roots"],
    "tags": ["quadratic"]
  },
  {
    "id": "MATH_022",
    "subject": "Mathematics",
    "chapter": "Sequences and Series",
    "topic": "AP",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Find the 15th term of AP: 3,7,11,...",
    "correctAnswer": 59,
    "solution": "a₁₅ = 3 + 14×4 = 59.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 90,
    "concepts": ["AP nth term"],
    "tags": ["ap"]
  },
  {
    "id": "MATH_023",
    "subject": "Mathematics",
    "chapter": "Binomial Theorem",
    "topic": "Expansion",
    "difficulty": "Hard",
    "type": "NUMERICAL",
    "question": "Find coefficient of x³ in (1+x)^5.",
    "correctAnswer": 10,
    "solution": "5C3 = 10.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 120,
    "concepts": ["Binomial coefficient"],
    "tags": ["binomial"]
  },
  {
    "id": "MATH_024",
    "subject": "Mathematics",
    "chapter": "Straight Lines",
    "topic": "Slope",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Find slope of line joining points (2,3) and (6,11).",
    "correctAnswer": 2,
    "solution": "(11−3)/(6−2)=2.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 90,
    "concepts": ["Slope"],
    "tags": ["straight-lines"]
  },
  {
    "id": "MATH_025",
    "subject": "Mathematics",
    "chapter": "Probability",
    "topic": "Coin Toss",
    "difficulty": "Easy",
    "type": "NUMERICAL",
    "question": "A coin is tossed twice. Number of possible outcomes is:",
    "correctAnswer": 4,
    "solution": "HH, HT, TH, TT.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 45,
    "concepts": ["Sample space"],
    "tags": ["probability"]
  }
];

const physicsQuestions = [
  {
    "id": "PHY_001",
    "subject": "Physics",
    "chapter": "Units and Measurements",
    "topic": "Significant Figures",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Dheeraj measured the length of a classroom in Dharmavaram as 12.340 m. The number of significant figures is:",
    "options": ["3", "4", "5", "6"],
    "correctAnswer": "5",
    "solution": "All non-zero digits and trailing zeros after decimal are significant.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Significant figures"],
    "tags": ["units", "measurement"]
  },
  {
    "id": "PHY_002",
    "subject": "Physics",
    "chapter": "Kinematics",
    "topic": "Average Speed",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Harsha rides his bike from Kadiri to Dharmavaram covering 60 km in 2 hours. His average speed is:",
    "options": ["20 km/h", "30 km/h", "40 km/h", "60 km/h"],
    "correctAnswer": "30 km/h",
    "solution": "Average speed = distance/time = 60/2.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Average speed"],
    "tags": ["kinematics"]
  },
  {
    "id": "PHY_003",
    "subject": "Physics",
    "chapter": "Kinematics",
    "topic": "Projectile Motion",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Chintu throws a cricket ball vertically upward with speed 20 m/s. Maximum height reached is approximately: (g = 10 m/s²)",
    "options": ["10 m", "20 m", "30 m", "40 m"],
    "correctAnswer": "20 m",
    "solution": "h = u²/2g = 400/20 = 20 m.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Projectile motion"],
    "tags": ["kinematics", "motion"]
  },
  {
    "id": "PHY_004",
    "subject": "Physics",
    "chapter": "Laws of Motion",
    "topic": "Newton's Second Law",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Maneesh Anna pushes a cart of mass 5 kg with force 20 N. The acceleration produced is:",
    "options": ["2 m/s²", "4 m/s²", "5 m/s²", "10 m/s²"],
    "correctAnswer": "4 m/s²",
    "solution": "a = F/m = 20/5 = 4.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Newton's laws"],
    "tags": ["force"]
  },
  {
    "id": "PHY_005",
    "subject": "Physics",
    "chapter": "Laws of Motion",
    "topic": "Friction",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "A wooden block remains at rest on a rough surface because:",
    "options": [
      "No force acts",
      "Static friction balances force",
      "Kinetic friction acts",
      "Gravity disappears"
    ],
    "correctAnswer": "Static friction balances force",
    "solution": "Static friction opposes impending motion.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Friction"],
    "tags": ["friction"]
  },
  {
    "id": "PHY_006",
    "subject": "Physics",
    "chapter": "Work Energy and Power",
    "topic": "Kinetic Energy",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Nandhu rides a scooter of total mass 100 kg at 10 m/s. The kinetic energy is:",
    "options": ["1000 J", "2000 J", "5000 J", "10000 J"],
    "correctAnswer": "5000 J",
    "solution": "KE = 1/2 mv² = 0.5×100×100.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Kinetic energy"],
    "tags": ["energy"]
  },
  {
    "id": "PHY_007",
    "subject": "Physics",
    "chapter": "Work Energy and Power",
    "topic": "Power",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Harsha lifts a 50 N box by 2 m in 5 s. Power developed is:",
    "options": ["10 W", "20 W", "25 W", "50 W"],
    "correctAnswer": "20 W",
    "solution": "Power = Work/time = (50×2)/5.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Power"],
    "tags": ["work-energy"]
  },
  {
    "id": "PHY_008",
    "subject": "Physics",
    "chapter": "Rotational Motion",
    "topic": "Angular Momentum",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "A spinning fan continues rotating after power is switched off due to:",
    "options": [
      "Newton’s first law",
      "Conservation of angular momentum",
      "Friction",
      "Gravity"
    ],
    "correctAnswer": "Conservation of angular momentum",
    "solution": "Angular momentum resists change.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Angular momentum"],
    "tags": ["rotation"]
  },
  {
    "id": "PHY_009",
    "subject": "Physics",
    "chapter": "Gravitation",
    "topic": "Acceleration due to gravity",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "The approximate value of g near Earth's surface is:",
    "options": ["5 m/s²", "9.8 m/s²", "15 m/s²", "20 m/s²"],
    "correctAnswer": "9.8 m/s²",
    "solution": "Standard gravitational acceleration.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 30,
    "concepts": ["Gravity"],
    "tags": ["gravitation"]
  },
  {
    "id": "PHY_010",
    "subject": "Physics",
    "chapter": "Gravitation",
    "topic": "Escape Velocity",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Escape velocity from Earth is approximately:",
    "options": ["7.9 km/s", "11.2 km/s", "15 km/s", "20 km/s"],
    "correctAnswer": "11.2 km/s",
    "solution": "Standard escape velocity value.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Escape velocity"],
    "tags": ["gravitation"]
  },
  {
    "id": "PHY_011",
    "subject": "Physics",
    "chapter": "Properties of Matter",
    "topic": "Hooke's Law",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "The restoring force in a spring is proportional to displacement according to:",
    "options": [
      "Newton's law",
      "Hooke's law",
      "Ohm's law",
      "Kepler's law"
    ],
    "correctAnswer": "Hooke's law",
    "solution": "F = -kx.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Elasticity"],
    "tags": ["springs"]
  },
  {
    "id": "PHY_012",
    "subject": "Physics",
    "chapter": "Oscillations",
    "topic": "Simple Harmonic Motion",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Time period of a simple pendulum depends on:",
    "options": [
      "Mass",
      "Amplitude",
      "Length",
      "Shape"
    ],
    "correctAnswer": "Length",
    "solution": "T = 2π√(l/g).",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["SHM"],
    "tags": ["oscillations"]
  },
  {
    "id": "PHY_013",
    "subject": "Physics",
    "chapter": "Waves",
    "topic": "Wave Speed",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Wave speed is given by:",
    "options": ["v=f/λ", "v=fλ", "v=λ/f", "v=f²λ"],
    "correctAnswer": "v=fλ",
    "solution": "Standard wave equation.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Wave motion"],
    "tags": ["waves"]
  },
  {
    "id": "PHY_014",
    "subject": "Physics",
    "chapter": "Kinematics",
    "topic": "Uniform Acceleration",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "A car accelerates uniformly from 0 to 20 m/s in 5 s. Acceleration is:",
    "options": ["2", "4", "5", "10"],
    "correctAnswer": "4",
    "solution": "a=(v-u)/t = 20/5.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Acceleration"],
    "tags": ["motion"]
  },
  {
    "id": "PHY_015",
    "subject": "Physics",
    "chapter": "Units and Measurements",
    "topic": "Dimensional Analysis",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Dimension of force is:",
    "options": [
      "MLT⁻¹",
      "ML²T⁻²",
      "MLT⁻²",
      "M⁰LT⁻²"
    ],
    "correctAnswer": "MLT⁻²",
    "solution": "Force = mass × acceleration.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Dimensions"],
    "tags": ["dimensions"]
  },
  {
    "id": "PHY_016",
    "subject": "Physics",
    "chapter": "Rotational Motion",
    "topic": "Torque",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Torque is defined as:",
    "options": [
      "Force × distance",
      "Mass × acceleration",
      "Force × perpendicular distance",
      "Momentum × velocity"
    ],
    "correctAnswer": "Force × perpendicular distance",
    "solution": "τ = rF sinθ.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Torque"],
    "tags": ["rotation"]
  },
  {
    "id": "PHY_017",
    "subject": "Physics",
    "chapter": "Waves",
    "topic": "Standing Waves",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Resonance occurs when frequency of external force becomes equal to:",
    "options": [
      "Zero",
      "Natural frequency",
      "Double frequency",
      "Half frequency"
    ],
    "correctAnswer": "Natural frequency",
    "solution": "Condition for resonance.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Resonance"],
    "tags": ["waves"]
  },
  {
    "id": "PHY_018",
    "subject": "Physics",
    "chapter": "Properties of Matter",
    "topic": "Pressure",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Pressure is defined as:",
    "options": [
      "Force × Area",
      "Force/Area",
      "Area/Force",
      "Mass × Volume"
    ],
    "correctAnswer": "Force/Area",
    "solution": "P = F/A.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 30,
    "concepts": ["Pressure"],
    "tags": ["fluids"]
  },
  {
    "id": "PHY_019",
    "subject": "Physics",
    "chapter": "Oscillations",
    "topic": "Frequency",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Frequency is the reciprocal of:",
    "options": [
      "Amplitude",
      "Velocity",
      "Time period",
      "Displacement"
    ],
    "correctAnswer": "Time period",
    "solution": "f = 1/T.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Frequency"],
    "tags": ["oscillation"]
  },
  {
    "id": "PHY_020",
    "subject": "Physics",
    "chapter": "Work Energy and Power",
    "topic": "Conservation of Energy",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "A freely falling object converts:",
    "options": [
      "Kinetic energy to potential energy",
      "Potential energy to kinetic energy",
      "Heat to light",
      "Mass to energy"
    ],
    "correctAnswer": "Potential energy to kinetic energy",
    "solution": "Mechanical energy conversion during fall.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Energy conservation"],
    "tags": ["energy"]
  },
  {
    "id": "PHY_021",
    "subject": "Physics",
    "chapter": "Kinematics",
    "topic": "Velocity",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Chinna runs 100 m in 20 s. Find his speed in m/s.",
    "correctAnswer": 5,
    "solution": "Speed = distance/time = 100/20.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 60,
    "concepts": ["Speed"],
    "tags": ["kinematics"]
  },
  {
    "id": "PHY_022",
    "subject": "Physics",
    "chapter": "Laws of Motion",
    "topic": "Force",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Find force required to accelerate a 4 kg object at 3 m/s².",
    "correctAnswer": 12,
    "solution": "F = ma = 4×3.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 75,
    "concepts": ["Newton's second law"],
    "tags": ["force"]
  },
  {
    "id": "PHY_023",
    "subject": "Physics",
    "chapter": "Work Energy and Power",
    "topic": "Work",
    "difficulty": "Easy",
    "type": "NUMERICAL",
    "question": "A 10 N force moves an object by 5 m. Calculate work done.",
    "correctAnswer": 50,
    "solution": "W = Fs = 10×5.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 60,
    "concepts": ["Work"],
    "tags": ["work"]
  },
  {
    "id": "PHY_024",
    "subject": "Physics",
    "chapter": "Gravitation",
    "topic": "Weight",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Find weight of a 6 kg object on Earth. (g = 10 m/s²)",
    "correctAnswer": 60,
    "solution": "W = mg = 6×10.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 60,
    "concepts": ["Weight"],
    "tags": ["gravity"]
  },
  {
    "id": "PHY_025",
    "subject": "Physics",
    "chapter": "Oscillations",
    "topic": "Time Period",
    "difficulty": "Hard",
    "type": "NUMERICAL",
    "question": "A pendulum completes 20 oscillations in 40 seconds. Find time period.",
    "correctAnswer": 2,
    "solution": "T = total time / oscillations = 40/20.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 75,
    "concepts": ["Time period"],
    "tags": ["shm"]
  }
];

const chemistryQuestions = [
  {
    "id": "CHEM_001",
    "subject": "Chemistry",
    "chapter": "Some Basic Concepts of Chemistry",
    "topic": "Mole Concept",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Amma is boiling water for tea. If 18 g of water is taken, the number of moles of water present is:",
    "options": ["0.5", "1", "2", "18"],
    "correctAnswer": "1",
    "solution": "Moles = mass/molar mass = 18/18 = 1.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Mole concept"],
    "tags": ["mole", "stoichiometry"]
  },
  {
    "id": "CHEM_002",
    "subject": "Chemistry",
    "chapter": "States of Matter",
    "topic": "Gas Laws",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Dheeraj inflated a balloon in summer. The balloon expanded mainly because:",
    "options": [
      "Pressure decreases",
      "Temperature increases gas volume",
      "Mass increases",
      "Gravity decreases"
    ],
    "correctAnswer": "Temperature increases gas volume",
    "solution": "According to Charles’ law, volume increases with temperature.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Charles law"],
    "tags": ["gases"]
  },
  {
    "id": "CHEM_003",
    "subject": "Chemistry",
    "chapter": "Thermodynamics",
    "topic": "Enthalpy",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Amma cooks rice in a pressure cooker because increased pressure:",
    "options": [
      "Decreases boiling point",
      "Increases boiling point",
      "Stops evaporation",
      "Converts water into steam permanently"
    ],
    "correctAnswer": "Increases boiling point",
    "solution": "Higher pressure raises boiling point allowing faster cooking.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Boiling point"],
    "tags": ["thermodynamics", "daily-life"]
  },
  {
    "id": "CHEM_004",
    "subject": "Chemistry",
    "chapter": "Equilibrium",
    "topic": "Le Chatelier Principle",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "When concentration of reactants increases, equilibrium shifts:",
    "options": [
      "Backward",
      "Forward",
      "Stops reaction",
      "No effect"
    ],
    "correctAnswer": "Forward",
    "solution": "System opposes increase in reactants.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Chemical equilibrium"],
    "tags": ["equilibrium"]
  },
  {
    "id": "CHEM_005",
    "subject": "Chemistry",
    "chapter": "Redox Reactions",
    "topic": "Oxidation",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Rusting of iron is an example of:",
    "options": [
      "Reduction",
      "Oxidation",
      "Neutralization",
      "Combustion"
    ],
    "correctAnswer": "Oxidation",
    "solution": "Iron combines with oxygen.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Oxidation"],
    "tags": ["redox"]
  },
  {
    "id": "CHEM_006",
    "subject": "Chemistry",
    "chapter": "Atomic Structure",
    "topic": "Atomic Number",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Atomic number represents:",
    "options": [
      "Neutrons",
      "Electrons only",
      "Protons",
      "Mass number"
    ],
    "correctAnswer": "Protons",
    "solution": "Atomic number equals number of protons.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Atomic structure"],
    "tags": ["atoms"]
  },
  {
    "id": "CHEM_007",
    "subject": "Chemistry",
    "chapter": "Periodic Classification",
    "topic": "Periodic Trends",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Atomic radius generally decreases across a period because:",
    "options": [
      "Mass decreases",
      "Nuclear charge increases",
      "Electrons disappear",
      "Shells decrease"
    ],
    "correctAnswer": "Nuclear charge increases",
    "solution": "Electrons pulled closer to nucleus.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Periodic trends"],
    "tags": ["periodic-table"]
  },
  {
    "id": "CHEM_008",
    "subject": "Chemistry",
    "chapter": "Chemical Bonding",
    "topic": "Covalent Bonding",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "In H₂ molecule, bond formation occurs by:",
    "options": [
      "Transfer of electrons",
      "Sharing of electrons",
      "Loss of neutrons",
      "Gain of protons"
    ],
    "correctAnswer": "Sharing of electrons",
    "solution": "Covalent bond forms by sharing electrons.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Covalent bond"],
    "tags": ["bonding"],
    "diagram": "/images/chemistry/h2-bond.png"
  },
  {
    "id": "CHEM_009",
    "subject": "Chemistry",
    "chapter": "Chemical Bonding",
    "topic": "Molecular Geometry",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "The shape of water molecule is:",
    "options": [
      "Linear",
      "Trigonal planar",
      "Bent",
      "Tetrahedral"
    ],
    "correctAnswer": "Bent",
    "solution": "Due to two lone pairs on oxygen.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["VSEPR"],
    "tags": ["molecular-shape"],
    "diagram": "/images/chemistry/h2o-bent-structure.png"
  },
  {
    "id": "CHEM_010",
    "subject": "Chemistry",
    "chapter": "Hydrogen",
    "topic": "Properties",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Hydrogen gas is:",
    "options": [
      "Heaviest gas",
      "Lightest gas",
      "Colored gas",
      "Liquid at room temperature"
    ],
    "correctAnswer": "Lightest gas",
    "solution": "Hydrogen has lowest molecular mass.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 30,
    "concepts": ["Hydrogen"],
    "tags": ["hydrogen"]
  },
  {
    "id": "CHEM_011",
    "subject": "Chemistry",
    "chapter": "s-Block Elements",
    "topic": "Alkali Metals",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Sodium is stored in kerosene because it:",
    "options": [
      "Is expensive",
      "Reacts with air and moisture",
      "Is radioactive",
      "Evaporates quickly"
    ],
    "correctAnswer": "Reacts with air and moisture",
    "solution": "Sodium is highly reactive.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Reactive metals"],
    "tags": ["s-block"]
  },
  {
    "id": "CHEM_012",
    "subject": "Chemistry",
    "chapter": "Organic Chemistry",
    "topic": "Hydrocarbons",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "LPG used in Amma’s kitchen mainly contains:",
    "options": [
      "Methane",
      "Propane and Butane",
      "Hydrogen",
      "Carbon monoxide"
    ],
    "correctAnswer": "Propane and Butane",
    "solution": "LPG primarily contains propane and butane.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Hydrocarbons"],
    "tags": ["organic", "daily-life"]
  },
  {
    "id": "CHEM_013",
    "subject": "Chemistry",
    "chapter": "Organic Chemistry",
    "topic": "Functional Groups",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Alcohol functional group is represented by:",
    "options": [
      "-CHO",
      "-OH",
      "-COOH",
      "-NH₂"
    ],
    "correctAnswer": "-OH",
    "solution": "Hydroxyl group represents alcohols.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 75,
    "concepts": ["Functional groups"],
    "tags": ["organic"]
  },
  {
    "id": "CHEM_014",
    "subject": "Chemistry",
    "chapter": "Environmental Chemistry",
    "topic": "Pollution",
    "difficulty": "Easy",
    "type": "MCQ",
    "question": "Acid rain mainly occurs due to:",
    "options": [
      "CO₂",
      "SO₂ and NOx",
      "O₂",
      "Hydrogen"
    ],
    "correctAnswer": "SO₂ and NOx",
    "solution": "Sulfur and nitrogen oxides cause acid rain.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Pollution"],
    "tags": ["environment"]
  },
  {
    "id": "CHEM_015",
    "subject": "Chemistry",
    "chapter": "Chemical Bonding",
    "topic": "Hybridization",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Hybridization of carbon in methane (CH₄) is:",
    "options": [
      "sp",
      "sp²",
      "sp³",
      "dsp²"
    ],
    "correctAnswer": "sp³",
    "solution": "Methane has tetrahedral geometry.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Hybridization"],
    "tags": ["bonding"],
    "diagram": "/images/chemistry/ch4-sp3.png"
  },
  {
    "id": "CHEM_016",
    "subject": "Chemistry",
    "chapter": "States of Matter",
    "topic": "Ideal Gas Equation",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "The ideal gas equation is:",
    "options": [
      "PV=nRT",
      "E=mc²",
      "F=ma",
      "V=IR"
    ],
    "correctAnswer": "PV=nRT",
    "solution": "Standard ideal gas equation.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Gas laws"],
    "tags": ["physical-chemistry"]
  },
  {
    "id": "CHEM_017",
    "subject": "Chemistry",
    "chapter": "Thermodynamics",
    "topic": "Exothermic Reactions",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "Burning LPG in a stove is an example of:",
    "options": [
      "Endothermic reaction",
      "Exothermic reaction",
      "Neutralization",
      "Electrolysis"
    ],
    "correctAnswer": "Exothermic reaction",
    "solution": "Heat is released.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Thermochemistry"],
    "tags": ["thermodynamics"]
  },
  {
    "id": "CHEM_018",
    "subject": "Chemistry",
    "chapter": "Equilibrium",
    "topic": "Dynamic Equilibrium",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "At chemical equilibrium:",
    "options": [
      "Reaction stops",
      "Forward and backward reactions continue at equal rates",
      "Only backward reaction occurs",
      "Concentration becomes zero"
    ],
    "correctAnswer": "Forward and backward reactions continue at equal rates",
    "solution": "Dynamic equilibrium condition.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 90,
    "concepts": ["Equilibrium"],
    "tags": ["equilibrium"]
  },
  {
    "id": "CHEM_019",
    "subject": "Chemistry",
    "chapter": "Organic Chemistry",
    "topic": "Alkanes",
    "difficulty": "Medium",
    "type": "MCQ",
    "question": "General formula of alkanes is:",
    "options": [
      "CnH2n",
      "CnH2n+2",
      "CnH2n-2",
      "CnHn"
    ],
    "correctAnswer": "CnH2n+2",
    "solution": "General formula for saturated hydrocarbons.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 60,
    "concepts": ["Hydrocarbons"],
    "tags": ["organic"]
  },
  {
    "id": "CHEM_020",
    "subject": "Chemistry",
    "chapter": "Periodic Classification",
    "topic": "Electronegativity",
    "difficulty": "Hard",
    "type": "MCQ",
    "question": "Most electronegative element is:",
    "options": [
      "Oxygen",
      "Nitrogen",
      "Fluorine",
      "Chlorine"
    ],
    "correctAnswer": "Fluorine",
    "solution": "Fluorine has highest electronegativity.",
    "marks": 4,
    "negativeMarks": 1,
    "estimatedTime": 45,
    "concepts": ["Periodic properties"],
    "tags": ["periodic-table"]
  },
  {
    "id": "CHEM_021",
    "subject": "Chemistry",
    "chapter": "Mole Concept",
    "topic": "Molar Mass",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Calculate number of moles in 44 g of CO₂.",
    "correctAnswer": 1,
    "solution": "Moles = 44/44 = 1.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 75,
    "concepts": ["Moles"],
    "tags": ["stoichiometry"]
  },
  {
    "id": "CHEM_022",
    "subject": "Chemistry",
    "chapter": "Thermodynamics",
    "topic": "Heat",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "If 100 J work is done and internal energy increases by 50 J, heat supplied is:",
    "correctAnswer": 150,
    "solution": "Q = ΔU + W = 50 + 100.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 120,
    "concepts": ["First law of thermodynamics"],
    "tags": ["thermodynamics"]
  },
  {
    "id": "CHEM_023",
    "subject": "Chemistry",
    "chapter": "Gas Laws",
    "topic": "Boyle's Law",
    "difficulty": "Hard",
    "type": "NUMERICAL",
    "question": "Pressure of a gas doubles. If temperature remains constant, final volume becomes what fraction of original volume?",
    "correctAnswer": 0.5,
    "solution": "P₁V₁=P₂V₂, hence V₂=V₁/2.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 90,
    "concepts": ["Boyle law"],
    "tags": ["gases"]
  },
  {
    "id": "CHEM_024",
    "subject": "Chemistry",
    "chapter": "Chemical Bonding",
    "topic": "Valency",
    "difficulty": "Easy",
    "type": "NUMERICAL",
    "question": "Find valency of oxygen in H₂O.",
    "correctAnswer": 2,
    "solution": "Oxygen forms two bonds.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 45,
    "concepts": ["Valency"],
    "tags": ["bonding"]
  },
  {
    "id": "CHEM_025",
    "subject": "Chemistry",
    "chapter": "Organic Chemistry",
    "topic": "Carbon Chains",
    "difficulty": "Medium",
    "type": "NUMERICAL",
    "question": "Number of carbon atoms present in propane is:",
    "correctAnswer": 3,
    "solution": "Propane = C₃H₈.",
    "marks": 4,
    "negativeMarks": 0,
    "estimatedTime": 45,
    "concepts": ["Hydrocarbons"],
    "tags": ["organic"]
  }
];

export async function POST(req: Request) {
  try {
    await connectToDatabase();

    // Clear existing questions to avoid any duplicates and maintain a clean state
    await Question.deleteMany({});

    // Normalize and add missing blueprint fields for Mathematics questions
    const formattedMath = mathQuestions.map((q) => ({
      ...q,
      examType: "JEE_MAIN",
      pyq: false,
    }));

    // Normalize and add missing blueprint fields for Physics questions
    const formattedPhysics = physicsQuestions.map((q) => ({
      ...q,
      examType: "JEE_MAIN",
      pyq: false,
    }));

    // Normalize and add missing blueprint fields for Chemistry questions
    const formattedChemistry = chemistryQuestions.map((q) => ({
      ...q,
      examType: "JEE_MAIN",
      pyq: false,
    }));

    // Seed questions
    const seededMath = await Question.insertMany(formattedMath);
    const seededPhysics = await Question.insertMany(formattedPhysics);
    const seededChemistry = await Question.insertMany(formattedChemistry);

    return NextResponse.json({
      success: true,
      message: `Database successfully seeded!`,
      seededMathCount: seededMath.length,
      seededPhysicsCount: seededPhysics.length,
      seededChemistryCount: seededChemistry.length,
      totalSeeded: seededMath.length + seededPhysics.length + seededChemistry.length
    });
  } catch (error: any) {
    console.error("Database seeding failed:", error);
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
